<?php

use Faker\Generator as Faker;

$factory->define(App\Listing::class, function (Faker $faker) {
    return [
        'acreage'             => $faker->numberBetween(.1, 15),
        'area'                => $faker->city,
        'baths'               => $faker->numberBetween(1, 15),
        'baths_full'          => $faker->numberBetween(1, 15),
        'baths_half'          => $faker->numberBetween(1, 15),
        'bedrooms'            => $faker->numberBetween(1, 15),
        'cib_front_footage'   => $faker->numberBetween(1, 15),
        'city'                => $faker->city,
        'co_la_code'          => $faker->randomNumber(9, true),
        'co_lo_code'          => $faker->randomNumber(9, true),
        'date_modified'       => $faker->date(),
        'directions'          => $faker->sentence,
        'ftr_constrc'         => $faker->sentence,
        'ftr_energy'          => $faker->sentence,
        'ftr_exterior'        => $faker->sentence,
        'ftr_hoaincl'         => $faker->sentence,
        'ftr_interior'        => $faker->sentence,
        'ftr_lotaccess'       => $faker->sentence,
        'ftr_lotdesc'         => $faker->sentence,
        'ftr_ownership'       => $faker->sentence,
        'ftr_parking'         => $faker->sentence,
        'ftr_projfacilities'  => $faker->sentence,
        'ftr_utilities'       => $faker->sentence,
        'ftr_waterfront'      => $faker->boolean(),
        'ftr_waterview'       => $faker->sentence,
        'ftr_zoning'          => $faker->sentence,
        'la_code'             => $faker->randomNumber(9, true),
        'legals'              => $faker->sentence,
        'list_date'           => $faker->date(),
        'list_price'          => $faker->numberBetween(100000, 9000000),
        'lot_dimensions'      => '140 x 304',
        'latitude'            => $faker->latitude,
        'longitude'           => $faker->longitude,
        'mls_acct'            => (string) $faker->unique()->randomNumber(6, true),
        'occupancy_yn'        => $faker->word,
        'original_list_price' => $faker->numberBetween(100000, 9000000),
        'parcel_id'           => $faker->randomNumber(9, true),
        'parking_spaces'      => $faker->numberBetween(1, 10),
        'photo_count'         => $faker->randomNumber(2, true),
        'photo_date_modified' => $faker->date(),
        'prop_type'           => 'Detached Single Family',
        'public_show_address' => $faker->streetAddress,
        'remarks'             => $faker->sentence,
        'res_hoa_fee'         => $faker->numberBetween(100, 3000),
        'res_hoa_term'        => $faker->word,
        'sa_code'             => $faker->randomNumber(9, true),
        'sold_date'           => $faker->date(),
        'sold_price'          => $faker->numberBetween(100000, 9000000),
        'so_code'             => $faker->randomNumber(9, true),
        'so_name'             => $faker->company,
        'sqft_total'          => $faker->numberBetween(100, 10000),
        'state'               => $faker->state,
        'status'              => 'Active',
        'stories'             => $faker->randomNumber(1),
        'street_name'         => $faker->streetName,
        'street_num'          => $faker->randomNumber(3),
        'subdivision'         => $faker->city,
        'sub_area'            => $faker->city,
        'tot_heat_sqft'       => $faker->numberBetween(100, 2000),
        'unit_num'            => $faker->randomNumber(2),
        'virtual_tour'        => 'http://google.com',
        'virtual_tour2'       => 'http://google.com',
        'wf_feet'             => $faker->randomNumber(2),
        'year_built'          => $faker->year(),
        'zip'                 => $faker->postcode
    ];
});
